safe: true
lsi: false
source: .
name: cultural coder
author: krzysztof siejkowski
deployurl: http://culturalcoder.com

future: true
permalink: :title

exclude: [CNAME, Gemfile, Gemfile.lock, README.md, _ideas/*]

highlighter: pygments
markdown: kramdown
